# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('Id', models.TextField(primary_key=True, serialize=False)),
                ('course', models.TextField(max_length=30)),
                ('couse_diff', models.TextField(max_length=30)),
                ('couse_des', models.TextField(max_length=30)),
                ('link', models.TextField(max_length=30)),
                ('course_type', models.TextField(max_length=30)),
                ('course_author', models.TextField(max_length=30)),
                ('approval_status', models.BooleanField(default=False)),
            ],
        ),
    ]
