# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('ID', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('enroll_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.BooleanField(default=False)),
                ('solution', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(null=True)),
                ('ifACE', models.BooleanField()),
                ('ifCore', models.BooleanField()),
                ('domain', models.CharField(choices=[('a', 'Programming'), ('b', 'Web Development'), ('c', 'Graphic Desgning'), ('d', 'A/V Editing'), ('e', 'Other')], max_length=1)),
                ('enroll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acelibraryapp.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='author',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
