# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0002_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='Id',
        ),
        migrations.AddField(
            model_name='resources',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resources',
            name='course',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resources',
            name='course_author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resources',
            name='course_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resources',
            name='couse_des',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resources',
            name='couse_diff',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='resources',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
