# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-07 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acelibraryapp', '0002_auto_20161104_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='author',
        ),
    ]
